"""empty message 
Revision ID: 2624f2cf5ca9
Revises: 423482be81a5
Create Date: 2012-04-15 01:47:17.503308

"""

# revision identifiers, used by Alembic.
revision = '2624f2cf5ca9'
down_revision = '423482be81a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status', sa.Enum('new', 'assigned', 'accepted', 'finished', 'closed'), nullable=True))
    op.add_column('tickets', sa.Column('owner_member_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('reporter_member_id', sa.Integer(), nullable=True))
    op.execute("alter table tickets drop foreign key fk_member_id")
    op.drop_column('tickets', u'member_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column(u'member_id', sa.INTEGER(), nullable=True))
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name="fk_member_id"),
    op.drop_column('tickets', 'reporter_member_id')
    op.drop_column('tickets', 'owner_member_id')
    op.drop_column('tickets', 'status')
    ### end Alembic commands ###
