"""empty message

Revision ID: 41050d0a9a86
Revises: 2624f2cf5ca9
Create Date: 2012-04-15 04:16:59.363385

"""

# revision identifiers, used by Alembic.
revision = '41050d0a9a86'
down_revision = '2624f2cf5ca9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_name', sa.Unicode(length=255), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'tickets', sa.Column('milestone_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tickets', 'milestone_id')
    op.drop_table('milestones')
    ### end Alembic commands ###
