"""empty message

Revision ID: 423482be81a5
Revises: f0eb20498b0
Create Date: 2012-04-13 20:07:07.996117

"""

# revision identifiers, used by Alembic.
revision = '423482be81a5'
down_revision = 'f0eb20498b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('ticket_no', sa.Integer(), nullable=True),
    sa.Column('ticket_name', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'projects', sa.Column('ticket_counter', sa.Integer(), nullable=True, default=0))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'projects', 'ticket_counter')
    op.drop_table('tickets')
    ### end Alembic commands ###
