"""empty message

Revision ID: 4d46b1bd74d7
Revises: None
Create Date: 2012-04-13 08:14:39.706046

"""

# revision identifiers, used by Alembic.
revision = '4d46b1bd74d7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Unicode(length=255), nullable=True, unique=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
